# Generated by Django 4.2.7 on 2024-04-19 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachtrack_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='classId',
        ),
        migrations.AddField(
            model_name='schedule',
            name='className',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subjectName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacherId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
